### ISSUE TITLE
zIndex of editors  - version 0.0.42 (possible issue duplication)

### ISSUE THREAD

**Issue by IOZD** [TGFTech/angular-cesium#199] opened 2018-01-03 14:38 UTC
**Intended outcome:**
try to drag specific component-editor that is covered by other polygons and  the Intended outcome is that the chosen polygon will be dragged;

**Actual outcome:**

the chosen polygon or polyline cant be dragged because it is covered by other polygons.

**How to reproduce the issue:**

create 3 new polygons or polylines with the same size and locate them in the same position,,
try to edit the second polygon and move it - it won't work.

**Version**
- angular-cesium@0.0.42

**Comment by tomermoshe** [comment] 2018-01-08 14:18
duplicate of #191. Closing

**Closed by tomermoshe** 2018-01-08 14:18 UTC
